### PR TITLE
Add JSHint

### PR DESCRIPTION
**Pull request by arthurvr**
As I said, jshint. If you don't like the settings, feel free to complain.

### CODE REVIEW

**Comment by johno** [comment]
Looks great! I will merge and publish as soon as Travis is done. Thank you.

**Comment by johno** [comment]
Published to npm as `generator-p@1.0.7`.

**Comment by arthurvr** [comment]
> Published to npm as generator-p@1.0.7.

Semver-wise that seems incorrect.

**Comment by johno** [comment]
Yeah, that is a good point. And I also just noticed, since I didn't have jshint installed globally on this machine, that a dev-dependency should be added for jshint.

**Comment by johno** [comment]
Also, I'm going to go ahead and add a `.jshintignore` to ignore `node_modules/`.

**Comment by arthurvr** [comment]
Nah. That's something for a global jshintignore.

**Comment by johno** [comment]
Oh word, if that's the common practice, we will defer to that.

**Comment by johno** [comment]
Published with `devDependency` for `jshint` as `generator-p@1.1.0`. Now with the correct semver, too : )

**Comment by arthurvr** [comment]
Thanks!

**Pull request merged**
